@startuml

title __CHAPTER_23's Class Diagram__\n

  namespace pattern_examples.bridge_pattern_example {
    abstract class pattern_examples.bridge_pattern_example.Car {
    }
  }
  

  namespace pattern_examples.bridge_pattern_example {
    class pattern_examples.bridge_pattern_example.Coupe {
    }
  }
  

  namespace pattern_examples.bridge_pattern_example {
    class pattern_examples.bridge_pattern_example.Hatchback {
    }
  }
  

  namespace pattern_examples.bridge_pattern_example {
    class pattern_examples.bridge_pattern_example.Kia {
    }
  }
  

  namespace pattern_examples.bridge_pattern_example {
    class pattern_examples.bridge_pattern_example.Main {
    }
  }
  

  namespace pattern_examples.bridge_pattern_example {
    interface pattern_examples.bridge_pattern_example.Make {
    }
  }
  

  namespace pattern_examples.bridge_pattern_example {
    class pattern_examples.bridge_pattern_example.Mresedes {
    }
  }
  

  namespace pattern_examples.bridge_pattern_example {
    class pattern_examples.bridge_pattern_example.Sedan {
    }
  }
  

  namespace pattern_examples.bridge_pattern_example {
    class pattern_examples.bridge_pattern_example.Skoda {
    }
  }
  

  namespace pattern_examples.decorator_pattern_example {
    abstract class pattern_examples.decorator_pattern_example.Decorator {
    }
  }
  

  namespace pattern_examples.decorator_pattern_example {
    class pattern_examples.decorator_pattern_example.LeftBracketDecorator {
    }
  }
  

  namespace pattern_examples.decorator_pattern_example {
    class pattern_examples.decorator_pattern_example.Main {
    }
  }
  

  namespace pattern_examples.decorator_pattern_example {
    class pattern_examples.decorator_pattern_example.Printer {
    }
  }
  

  namespace pattern_examples.decorator_pattern_example {
    interface pattern_examples.decorator_pattern_example.PrinterInterface {
    }
  }
  

  namespace pattern_examples.decorator_pattern_example {
    class pattern_examples.decorator_pattern_example.QuotesDecorator {
    }
  }
  

  namespace pattern_examples.decorator_pattern_example {
    class pattern_examples.decorator_pattern_example.RightBracketDecorator {
    }
  }
  

  namespace pattern_examples.facade_pattern_example {
    class pattern_examples.facade_pattern_example.Computer {
    }
  }
  

  namespace pattern_examples.facade_pattern_example {
    class pattern_examples.facade_pattern_example.DVDRom {
    }
  }
  

  namespace pattern_examples.facade_pattern_example {
    class pattern_examples.facade_pattern_example.HDD {
    }
  }
  

  namespace pattern_examples.facade_pattern_example {
    class pattern_examples.facade_pattern_example.Main {
    }
  }
  

  namespace pattern_examples.facade_pattern_example {
    class pattern_examples.facade_pattern_example.Power {
    }
  }
  

  pattern_examples.bridge_pattern_example.Car o-- pattern_examples.bridge_pattern_example.Make : make
  pattern_examples.bridge_pattern_example.Coupe -up-|> pattern_examples.bridge_pattern_example.Car
  pattern_examples.bridge_pattern_example.Hatchback -up-|> pattern_examples.bridge_pattern_example.Car
  pattern_examples.bridge_pattern_example.Kia .up.|> pattern_examples.bridge_pattern_example.Make
  pattern_examples.bridge_pattern_example.Mresedes .up.|> pattern_examples.bridge_pattern_example.Make
  pattern_examples.bridge_pattern_example.Sedan -up-|> pattern_examples.bridge_pattern_example.Car
  pattern_examples.bridge_pattern_example.Skoda .up.|> pattern_examples.bridge_pattern_example.Make
  pattern_examples.decorator_pattern_example.Decorator .up.|> pattern_examples.decorator_pattern_example.PrinterInterface
  pattern_examples.decorator_pattern_example.Decorator o-- pattern_examples.decorator_pattern_example.PrinterInterface : component
  pattern_examples.decorator_pattern_example.LeftBracketDecorator -up-|> pattern_examples.decorator_pattern_example.Decorator
  pattern_examples.decorator_pattern_example.Printer .up.|> pattern_examples.decorator_pattern_example.PrinterInterface
  pattern_examples.decorator_pattern_example.QuotesDecorator -up-|> pattern_examples.decorator_pattern_example.Decorator
  pattern_examples.decorator_pattern_example.RightBracketDecorator -up-|> pattern_examples.decorator_pattern_example.Decorator
  pattern_examples.facade_pattern_example.Computer o-- pattern_examples.facade_pattern_example.DVDRom : dvdRom
  pattern_examples.facade_pattern_example.Computer o-- pattern_examples.facade_pattern_example.HDD : hdd
  pattern_examples.facade_pattern_example.Computer o-- pattern_examples.facade_pattern_example.Power : power


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
