@startuml

title __TASK_B_2's Class Diagram__\n

  namespace tasks.task_B_2 {
    class tasks.task_B_2.Composite {
        - texts : List<Texted>
        + addText()
        + showText()
    }
  }
  

  namespace tasks.task_B_2 {
    class tasks.task_B_2.Header {
        - header : String
        - words : List<Texted>
        + Header()
        + Header()
        + showText()
    }
  }
  

  namespace tasks.task_B_2 {
    class tasks.task_B_2.Main {
        {static} + main()
    }
  }
  

  namespace tasks.task_B_2 {
    class tasks.task_B_2.Pargraph {
        - paragraph : String
        - sentences : List<Texted>
        + Pargraph()
        + Pargraph()
        + showText()
    }
  }
  

  namespace tasks.task_B_2 {
    class tasks.task_B_2.Sentence {
        - headers : List<Texted>
        - sentence : String
        + Sentence()
        + Sentence()
        + showText()
    }
  }
  

  namespace tasks.task_B_2 {
    class tasks.task_B_2.Text {
        - pargraphs : List<Texted>
        - text : String
        + Text()
        + Text()
        + showText()
    }
  }
  

  namespace tasks.task_B_2 {
    interface tasks.task_B_2.Texted {
        {abstract} + showText()
    }
  }
  

  namespace tasks.task_B_2 {
    class tasks.task_B_2.Word {
        - words : String
        + Word()
        + showText()
        + toString()
    }
  }
  

  tasks.task_B_2.Header .up.|> tasks.task_B_2.Texted
  tasks.task_B_2.Pargraph .up.|> tasks.task_B_2.Texted
  tasks.task_B_2.Sentence .up.|> tasks.task_B_2.Texted
  tasks.task_B_2.Text .up.|> tasks.task_B_2.Texted
  tasks.task_B_2.Word .up.|> tasks.task_B_2.Texted


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
