@startuml

title __COMPOSITE_PATTERN_EXAMPLE's Class Diagram__\n

  namespace pattern_examples.composite_pattern_example {
    class pattern_examples.composite_pattern_example.Circle {
        + draw()
    }
  }
  

  namespace pattern_examples.composite_pattern_example {
    class pattern_examples.composite_pattern_example.Composite {
        - components : List<Shape>
        + addComponent()
        + draw()
        + removeComponent()
    }
  }
  

  namespace pattern_examples.composite_pattern_example {
    class pattern_examples.composite_pattern_example.Main {
        {static} + main()
    }
  }
  

  namespace pattern_examples.composite_pattern_example {
    interface pattern_examples.composite_pattern_example.Shape {
        {abstract} + draw()
    }
  }
  

  namespace pattern_examples.composite_pattern_example {
    class pattern_examples.composite_pattern_example.Square {
        + draw()
    }
  }
  

  namespace pattern_examples.composite_pattern_example {
    class pattern_examples.composite_pattern_example.Triangle {
        + draw()
    }
  }
  

  pattern_examples.composite_pattern_example.Circle .up.|> pattern_examples.composite_pattern_example.Shape
  pattern_examples.composite_pattern_example.Composite .up.|> pattern_examples.composite_pattern_example.Shape
  pattern_examples.composite_pattern_example.Square .up.|> pattern_examples.composite_pattern_example.Shape
  pattern_examples.composite_pattern_example.Triangle .up.|> pattern_examples.composite_pattern_example.Shape


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
